version: '3'
services:
  appserver:
    build:
      context: .
      dockerfile: DockerfileAppServer
    container_name: appserver
    ports:
      - "3000:3000"
    volumes:
      - C://appl//config//:/appserver/app/controller/config/:rw 
    command: npm run start
    networks:
      - backend
networks:
  backend:
    driver: bridge
